logging:
  level:
    root: info
    org:
      hibernate:
        SQL: FALSE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
      springframework:
        security: DEBUG
#    org.springframework.security: DEBUG
#    com.packshop.api.modules.identity: DEBUG
