logging:
  level:
    org:
      hibernate:
        SQL: FALSE
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
#    org.springframework.security: DEBUG
#    com.packshop.api.modules.identity: DEBUG
