name: Java CI/CD

on:
  push:
    branches: ["main", "feature"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      # Build and test the API module
      - name: Build and Test API
        run: |
          cd API
          mvn clean install -B
          mvn test

      # Build and test the Client module
      - name: Build and Test Client
        run: |
          cd Client
          mvn clean install -B
          mvn test

      # Cache Maven packages
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

  security-scan:
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "Pack-Shop"
          path: "."
          format: "HTML"

      - name: Upload security scan results
        uses: actions/upload-artifact@v3
        with:
          name: dependency-check-report
          path: reports

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: [build-and-test, security-scan]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"

      - name: Build API for deployment
        run: |
          cd API
          mvn clean package -DskipTests

      - name: Build Client for deployment
        run: |
          cd Client
          mvn clean package -DskipTests
